### ISSUE TITLE
Add Halo by Beyonce to EmojiBops

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojibops#106]
Song Info: https://en.wikipedia.org/wiki/Halo_(Beyonc%C3%A9_song)

**Comment by mtloria** [comment]
Hi! Can I work on adding this card (as an aside, I will probably wait to put up a PR until Hacktoberfest officially starts on 10/1)?

**Comment by brittanyrw** [comment]
@mtloria Yep, no problem. Take all the time you need. 💖
