### ISSUE TITLE
Add Brown Skin Girl by Beyonce to EmojiBops

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojibops#107]
Song Info: https://en.wikipedia.org/wiki/Brown_Skin_Girl

**Comment by itssadon** [comment]
Hi! Can I work on adding this card (as an aside, I will probably wait to put up a PR until Hacktoberfest officially starts on 10/1)?

**Comment by brittanyrw** [comment]
@itssadon Yep, I will assign this to you. Thanks for working on this! 💖
