### ISSUE TITLE
Add link to other open source projects (EmojiScreen, etc)

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojibops#12]
Link to other open source projects that I have created.

Add a link to EmojiScreen (https://emojiscreen.com) and EmojiPages (https://emojipages.com) somewhere on the homepage.

Right now it seems like the only logical place is the footer area but open to suggestions. Feel free to add in a quick wireframe or sketch of what you are thinking before you start coding.

**Comment by MaximeKoitsalu** [comment]
Hi, I could take on this challenge. I was thinking of adding something like this: https://wireframe.cc/wnJMe4

**Comment by MaximeKoitsalu** [comment]
Actually, I've reached my 4 contributions limit. So if anyone else wants to take it! Feel free 🐱‍👤
