### ISSUE TITLE
Add Link to Spotify and Youtube Playlists to EmojiBops homepage

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojibops#135]
I have created Spotify and Youtube playlists for all of the EmojiBops songs and will add songs as they are added to the project! Add the link to the playlists inside of the header (red area).

Spotify Link: https://open.spotify.com/playlist/2EHUrlY5SJssqnD3FJDV6a?si=UGrdw8cZQ1K_cjQ7Ekh04g
Youtube Playlist Link: https://www.youtube.com/watch?v=RXt_lya0gto&list=PLZNYKAau0mPLN9ZzL3OODBUFHvYuVShJ1

Use the Spotify font awesome icon: https://fontawesome.com/icons/spotify?style=brands
Use the Youtube font awesome icon: https://fontawesome.com/icons/youtube

Add the link like a button similar to the image below: 
<img width="741" alt="Screen Shot 2019-09-29 at 11 31 12 PM" src="https://user-images.githubusercontent.com/23530405/65847854-40a4c480-e311-11e9-82cf-351eb0b0684f.png">

Feel free to suggest other designs or locations for the links. Let us know if you need more guidance for this issue.

**Comment by MrEvertide** [comment]
I will take on the issue for the Hactoberfest
