### ISSUE TITLE
Add I See Fire by Ed Sheeran to EmojiBops

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojibops#236]
Link: https://en.wikipedia.org/wiki/I_See_Fire

**Comment by tomial** [comment]
Let me do this :smile:

**Comment by Chinmayrane16** [comment]
@tomial I have already done this.. And just submitting a PR now!

**Comment by tomial** [comment]
> @tomial I have already done this.. And just submitting a PR now!

Okay,sry,I'll find another one song

**Comment by Chinmayrane16** [comment]
> > @tomial I have already done this.. And just submitting a PR now!
> 
> Okay,sry,I'll find another one song

Yeah thanks :)
