### ISSUE TITLE
Improve song card title display

### ISSUE THREAD

**Issue by felipeemarcon** [brittanyrw/emojibops#297]
I think that we could improve how song card title is displayed.

**Here is how it is currently:**
![image](https://user-images.githubusercontent.com/28930538/65981945-8b792600-e450-11e9-8087-dd28624b03e5.png)

**And if we make this like that?**
![image](https://user-images.githubusercontent.com/28930538/65982248-499caf80-e451-11e9-8c8f-8e327e9cab23.png)

When user click in a item, the song title appears over the icons (like last image), and don't bellow. To close the title, a icon with "**x**" can be clicked in top right corner.

What you think? Let me know. I wanna help improve this project.

If this solution makes sense, I would like to implement that.

Thanks!

**Comment by brittanyrw** [comment]
I want to keep the current layout where you can see both the emojis and the title at the same time. So I am going to close this Issue. Thanks!
