### ISSUE TITLE
Add "Diamonds" by Rhianna to EmojiBops

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojibops#45]
Add Diamonds by Rhianna
https://en.wikipedia.org/wiki/Diamonds_(Rihanna_song)

**Comment by tomial** [comment]
I can do this :smile:

**Comment by tomial** [comment]
> I can do this 😄

#253

**Comment by tomial** [comment]
#253 #

**Comment by tomial** [comment]
Done! #253
