### ISSUE TITLE
Add "9 to 5" by Dolly Parton to EmojiBops

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojibops#73]
Song Info: https://en.wikipedia.org/wiki/9_to_5_(Dolly_Parton_song)

**Comment by LuigiLegion** [comment]
I'll be working on this one

**Comment by LuigiLegion** [comment]
Here is my PR for this song:
[https://github.com/brittanyrw/emojibops/pull/289](url)

**Comment by LuigiLegion** [comment]
Here is my PR for this song:
https://github.com/brittanyrw/emojibops/pull/293

**Comment by LuigiLegion** [comment]
Here is my PR for this song: https://github.com/brittanyrw/emojibops/pull/293
