### ISSUE TITLE
Add a 'back to top' button

### ISSUE THREAD

**Issue by brittanyrw** [brittanyrw/emojibops#94]
Add a button at the bottom of the page that will take the user back to the top of the page.

This will help with navigation once the number of emoji cards added has increased. The button should stay at the bottom of the page as the user scrolls so they can click it without being at the very bottom of the website.

**Comment by Seniru** [comment]
I can work on this @brittanyrw. But before starting can you tell me how the button should look like (i want information about colours, borders, etc)

**Comment by brittanyrw** [comment]
@Seniru Sure! Here is an example.

On Smashing Magazine's website, they have a back to top button. Here is what it looks like:
<img width="84" alt="Screen Shot 2019-09-25 at 1 41 50 PM" src="https://user-images.githubusercontent.com/23530405/65625668-49f10280-df9a-11e9-9af9-3daea7830a29.png">

You don't have to have an animation like theirs has, unless you want to add that. Using an arrow/up icon (you can use font awesome) inside of a shape like a square or circle should work.

Here is the Smashing Magazine website: https://www.smashingmagazine.com/
Here is a font awesome icon you can use: https://fontawesome.com/icons/chevron-up?style=solid

For colors, you can use one of these for the background:

Yellow: gold
Red: #ff7676
Purple: #c976ff
Green: #76ffd2
Blue: #76b4ff

For whatever color you use, use a white as the icon color or this dark gray #3c3a4a, depending on what would look better on the background color of the shape.

On the [EmojiScreen](https://emojiscreen.com) website, there is an expand/collapse button in the bottom right of the screen. This is an example of what this button style could look like as well: https://emojiscreen.com/

Let me know if you need more details. I can make you a wireframe as well if you need that.

**Comment by Seniru** [comment]
Thanks for the information. I'll go for a round bordered one because the 'eye' icon in emoji screen is also round. 
EDIT: I have another idea to make the button appear when the user scrolls down the page other than displaying it initially
